config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks}
  resources :subscriptions, only: [:new]
  post '/charges', controller: :subscriptions, action: :create
  resources :articles, only: [:index, :show]
  root controller: :articles, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  #private

  def user_not_authorized
    flash[:error] = 'You need to be a subscriber to access this content'
    redirect_to new_subscription_path
  end

  def authenticate_user!
    unless current_user
      flash[:error] = 'You need to be logged in to access this content'
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: :show

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    authorize @article
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController


  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    flash[:error] = 'That did not work!'
    redirect_to root_path
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def new
  end

  def create
    # 1. Create a customer with Stripe
    # 2. Create a charge for that customer
    # 3. If charge is okay, update the user status to subscriber = true
    # 4. Flash "Welcome as a subscriber!" and redirect to root path

    customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
                               customer: customer.id,
                               amount: 1000,
                               description: 'Subscription to News Service',
                               currency: 'sek'
    )

    if charge.paid?
      current_user.subscriber = true
      current_user.save
      redirect_to root_path, notice: 'Welcome as a subscriber!'
    else
      redirect_to new_subscriptions_path, error: 'WTF?'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def toast_for(resource)
    message = content_tag(:strong, "#{pluralize(resource.errors.count, 'error')} prohibited this #{resource.class.name.downcase} from being saved")
    message += content_tag(:ul) do
      resource.errors.full_messages.map do |item|
        concat(content_tag(:li, item))
      end
    end

    flash.now[:error] = message.html_safe
  end
end

app/views/articles/index.html.haml
- @articles.each do |article|
  %h2= link_to article.title, article_path(article)

app/views/articles/show.html.haml
%h1
  = @article.title
%p= @article.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title NewsRoom
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'

  %body
    %header.main-nav
      %nav
        %ul
          %li
            = link_to 'News Room', root_path, style: 'font-size: 1.5rem;'
        %ul
          - if current_user
            %li
              %span
                %i.fa.fa-user
                = current_user.email
                = link_to 'Log out', destroy_user_session_path, method: :delete
          -else
            %li= link_to 'Register', new_user_registration_path
            %li= link_to 'Login with Facebook', user_facebook_omniauth_authorize_path




    .container
      - if flash[:error]
        :javascript
          k$.growl({
            text: "#{flash[:error]}",
            type: 'alert-error',
            delay: 5000
          })
      - elsif flash[:notice]
        :javascript
          k$.growl({
            title: 'Cool',
            text: "#{flash[:notice]}",
            type: 'alert-success',
            delay: 5000
          })
      = yield

app/views/subscriptions/new.html.haml
%h1 Subscription
= form_with url: charges_path do
  %script.stripe-button{ src: 'https://checkout.stripe.com/checkout.js',
      data: {amount: 1000,
      description: 'Subscription to My News Service',
      key: "#{ENV['STRIPE_APP']}",
      currency: 'sek',
      email: "#{current_user.email if current_user}"}}